JoinEvent/urls.py
from django.urls import path
from . import views

app_name = 'JoinEvent'

urlpatterns = [
    path('', views.join, name='join')
    
]

JoinMember/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path
from JoinMember import views as MemberViews

app_name = 'JoinMember'

urlpatterns = [
    path('', MemberViews.CreateMember, name='CreateMember'),
]

about/urls.py
from django.urls import path
from .views import about

app_name = "about"

urlpatterns = [
    path("", about, name="about"),
]

event/urls.py
from django.urls import path
from .views import event
app_name = 'event'

urlpatterns = [
    path('', event, name = 'event'),
   # path('', directEvent, name = 'directEvent'),
]

landing/urls.py
from django.urls import path
from . import views

app_name = "landing"

urlpatterns =  [
    path('', views.landing, name='landing'),
    path('news', views.news, name='news'),
]

profile_user/urls.py
from django.urls import path
from .views import profile, get_events
app_name = 'profile_user'

urlpatterns = [
    path('', profile, name = 'profile'),
    path('get-events/', get_events, name = 'get_events'),
]

tugas1_ppw_b_12/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls'), name='home'),
    path('event/', include('event.urls')),
    path('join/', include('JoinMember.urls')),
    path('joinevent/', include('JoinEvent.urls')),
    path('about/', include('about.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here
     path('profile/', include('profile_user.urls')),
]

JoinEvent/models.py
from django.db import models
from event.models import Event

# Create your models here.
class Join(models.Model):
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)
    email = models.CharField(max_length=50, unique=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=1)

JoinMember/models.py
from django.db import models

class Member(models.Model):
	name = models.CharField(max_length=50)
	username = models.CharField(max_length=50, unique=True)
	email = models.CharField(max_length=50, unique=True)
	birthdate = models.DateField()
	adress = models.CharField(max_length=100)
	password = models.CharField(max_length=50)

	def __str__(self):
		return "{}".format(self.name)

about/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    comment = models.CharField(max_length = 200)

    class Meta:
        verbose_name_plural = "comments"

event/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateTimeField()
    place = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    photo = models.URLField(null=True, blank=True, default='')
    google_member_participants = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.name

landing/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    date = models.DateTimeField()

    class Meta:
        ordering = ('-date',)
        verbose_name_plural = "news"

login/models.py
from django.db import models

# Create your models here.

JoinEvent/forms.py
from django import forms
from event.models import Event

class JoinForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Username',
        'required': True,
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
        'required': True,
    }))

    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
        'required': True,
    })) 

    event = forms.ModelMultipleChoiceField(queryset=Event.objects.all())

JoinMember/forms.py
from django import forms
from .models import Member
from django.forms import ModelForm

class add_member(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    birthdate = forms.DateField()
    class Meta:
        model = Member
        fields = ["name","username","email","birthdate","adress","password"]

about/forms.py
from django import forms

class CommentForm(forms.Form):
    comment = forms.CharField(max_length=200,widget=forms.Textarea(attrs={
        'placeholder': 'Enter your comment here',
        'required': True,
        'class': 'comment-control',
        'id': 'comment', 
    }))

JoinEvent/views.py
from django.shortcuts import render, redirect
from .models import Join
from .forms import JoinForm

# Create your views here.
def join(request):
    if request.method == 'POST':
        form = JoinForm(request.POST)
        if form.is_valid():
            join = Join()
            join.username = form.cleaned_data['username']
            join.password = form.cleaned_data['password']
            join.email = form.cleaned_data['email']
            join.save()
        return redirect('/')
    else:
        form = JoinForm()
        return render(request, 'join.html', {'form': form})

JoinMember/views.py
from django.shortcuts import render
from .forms import add_member
from .models import Member
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.http import HttpResponse

def CreateMember(request):
	if request.method == "POST":
		form = add_member(request.POST)
		if form.is_valid():
			form_item = form.save(commit=True)
			form_item.save()
		return HttpResponseRedirect('/join')
	else:
		form = add_member()
	return render(request, 'JoinMember.html', {'form' : form})

about/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .forms import CommentForm
from .models import Comment

# Create your views here.
def about(request):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment()
            comment.comment = form.cleaned_data["comment"]
            comment.save()
        return redirect("/about/")
    else:
        form = CommentForm()
        comments = Comment.objects.all()
        return render(request, 'about.html', {'form': form, 'comments': comments})

event/views.py
from django.shortcuts import render
from .models import Event

# Create your views here.
def event(request):
    event = Event.objects.all()
    response = {"event":event}
    return render(request, 'event.html', response)

#def directEvent(request):
#	return render(request, 'login.html', response)

landing/views.py
from django.shortcuts import render
from .models import News

# Create your views here.
def landing(request):
    return render(request, 'landing.html')

def news(request):
    news = News.objects.all()
    response = {"news": news}
    return render(request, 'news.html', response)

login/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="shortcut icon" href="{% static 'icon.png' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <title>Student Union</title>
    </head>
    <body>
        {% include 'header.html' %}

        {% block content %} 
        
        {% endblock %}
        
        {% include 'footer.html' %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'smooth_scroll.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/about.js' %}"></script>
    </body>
</html>

templates/footer.html
{% load static from staticfiles %}

<nav class="navbar navbar-expand-lg navbar-light bg-light footer-content footer-split">
    <a href="https://www.facebook.com">
        <img class="img-size footer-icon-margin" src="{% static 'facebook.png' %}" alt="Facebook">
    </a>
    <a href="https://www.twitter.com">
        <img class="img-size footer-icon-margin" src="{% static 'twitter.png' %}" alt="Twitter">
    </a>
    <a href="https://www.instagram.com">
        <img class="img-size footer-icon-margin" src="{% static 'instagram.png' %}" alt="Twitter">
    </a>
    <a href="https://www.youtube.com">
        <img class="img-size footer-icon-margin" src="{% static 'youtube.png' %}" alt="Twitter">
    </a>
</nav>

templates/header.html
{% load static from staticfiles %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand nav-text" href="{% url 'landing:landing' %}">Student Union</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'landing:news' %}">News <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-text" href="{% url 'event:event' %}">Event</a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-text" href="{% url 'JoinMember:CreateMember' %}">Become a member</a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-text" href="{% url 'about:about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link nav-text" href="{% url 'JoinEvent:join' %}">Join an event</a>
            </li>
            {% endif %}
            <li>
                {% if user.is_authenticated %}
                        <a class="nav-link nav-text" href="{% url 'logout' %}">Log out</a>
                {% else %}
                    <a class="nav-link nav-text" href="{% url 'login' %}">Log in</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>